go-2361 Fix wrongly saved payment type
banda-health/idemp-plugins pull request #25
Opened 2022-08-30 15:23 UTC by andrewmoko

2022-08-30 16:17 UTC, kwburnett requested changes
Can you write a test for this as well?

2022-08-30 16:17 UTC, kwburnett commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
> +			MRefList paymentTypeReference = new Query(Env.getCtx(), MRefList.Table_Name,
```suggestion
			MRefList paymentTypeReference = referenceListDBService.getEntityByUuidFromDB(entity.getPaymentType().getUuid());
```

2022-08-30 16:17 UTC, kwburnett commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
> +					MRefList.COLUMNNAME_AD_Ref_List_UU + "=?", null)
```suggestion
```

2022-08-30 16:17 UTC, kwburnett commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
> +							.setParameters(entity.getPaymentType().getUuid()).first();
```suggestion
```

2022-08-30 16:17 UTC, kwburnett commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
>  		if (entity.getPaymentType() != null) {
I'm guessing this change will also break the payment form since it submits the value. Can you update that so it still works?

2022-09-01 07:59 UTC, andrewmoko commented
> 

I hope you don't mind helping out with the tests? Thanks

2022-09-01 08:02 UTC, andrewmoko commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
> +			MRefList paymentTypeReference = new Query(Env.getCtx(), MRefList.Table_Name,
done

2022-09-01 08:02 UTC, andrewmoko commented on idemp-rest/WEB-INF/src/org/bandahealth/idempiere/rest/service/db/PaymentDBService.java
> +					MRefList.COLUMNNAME_AD_Ref_List_UU + "=?", null)
done

2022-09-01 13:05 UTC, kwburnett commented
> > 
> 
> I hope you don't mind helping out with the tests? Thanks

Sure can! I'll get on it shortly.

2022-09-01 14:59 UTC, kwburnett reviewed
Kindly take a look at the tests. Would you like me to update the payments sent from the Debt Payment screen?

2022-09-01 16:23 UTC, andrewmoko commented
> Kindly take a look at the tests. Would you like me to update the payments sent from the Debt Payment screen?

cool, much appreciated! thanks

2022-09-02 15:09 UTC, andrewmoko commented
@kwburnett is this good for merging? thanks

2022-09-02 15:50 UTC, kwburnett commented
> @kwburnett is this good for merging? thanks

Sure is!

2022-09-02 15:51 UTC, kwburnett approved these changes

2022-09-02 17:46 UTC, andrewmoko commented
> > @kwburnett is this good for merging? thanks
> 
> Sure is!

Thanks!

2022-09-06 12:00 UTC, kwburnett approved these changes

2022-09-06 12:06 UTC, merged