go-2443 Get default expense category type from client
banda-health/idemp-plugins pull request #45
Opened 2022-11-03 08:58 UTC by andrewmoko

2022-11-03 10:11 UTC, kwburnett requested changes
Code change looks great! Can we have a test written for this?

2022-11-08 02:38 UTC, kwburnett requested changes
Will you run `npm run create-index` on this? It'll add the API files correctly so they can just be referenced from the folder.

2022-11-08 02:38 UTC, kwburnett commented on idemp-rest-test/testing/src/tests/charges.test.ts
> +import { expenseCategoryApi } from 'src/api/expenseCategories';
```suggestion
import { expenseCategoryApi } from '../api';
```

2022-11-08 06:57 UTC, andrewmoko commented
> Will you run `npm run create-index` on this? It'll add the API files correctly so they can just be referenced from the folder.

![npm-index](https://user-images.githubusercontent.com/6028400/200495727-d2bb7106-21e5-47d4-8f18-5ad5f401a982.png)

Getting that error. Any clue?

2022-11-08 11:43 UTC, kwburnett commented
> > Will you run `npm run create-index` on this? It'll add the API files correctly so they can just be referenced from the folder.
> 
> ![npm-index](https://user-images.githubusercontent.com/6028400/200495727-d2bb7106-21e5-47d4-8f18-5ad5f401a982.png)
> 
> Getting that error. Any clue?

Have you run `npm install` in the `idemp-rest-test/testing` directory?

2022-11-08 13:14 UTC, andrewmoko commented
> > > Will you run `npm run create-index` on this? It'll add the API files correctly so they can just be referenced from the folder.
> > 
> > 
> > ![npm-index](https://user-images.githubusercontent.com/6028400/200495727-d2bb7106-21e5-47d4-8f18-5ad5f401a982.png)
> > Getting that error. Any clue?
> 
> Have you run `npm install` in the `idemp-rest-test/testing` directory?

that was the issue. thanks

2022-11-08 15:56 UTC, kwburnett approved these changes

2022-11-09 11:19 UTC, merged